Repository 5-jojojojojo/5team, pull requests merged in 2023-09, with the labels that each got.

#7 [DESIGN][PACK] : 🎨 액티비티, 버튼, 라이브러리, drawable 파일 추가
  app/build.gradle
  app/src/main/java/com/android/youtubeproject/Fragment/VideoDetailFragment/VideoDetail.kt
  app/src/main/res/drawable/ic_video_detail_dislike_false.png
  app/src/main/res/drawable/ic_video_detail_dislike_true.png
  app/src/main/res/drawable/ic_video_detail_infomation.png
  app/src/main/res/drawable/ic_video_detail_like_false.png
  app/src/main/res/drawable/ic_video_detail_like_true.png
  app/src/main/res/drawable/ic_video_detail_more_vert.png
  app/src/main/res/drawable/ic_video_detail_share_false.png
  app/src/main/res/drawable/ic_video_detail_share_true.png
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/values/colors.xml
Labels: UI

#8 [FEAT] : ⚙️ 비디오 디테일 액티비티 진입시 애니메이션 효과 구현
  app/src/main/java/com/android/youtubeproject/Fragment/VideoDetailFragment/VideoDetail.kt
  app/src/main/res/anim/anim_video_detail.xml
  app/src/main/res/drawable/ic_video_detail_dummyimage.png
  app/src/main/res/drawable/ic_video_detail_dummyimage2.png
  app/src/main/res/drawable/video_detail_dialog_rounded_image.xml
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/dialog_video_detail_information.xml
Labels: feat

#10 [FEAT] : ⚙️ 상세 페이지의 비디오 공유 기능 구현
  app/build.gradle
  app/src/main/java/com/android/youtubeproject/Fragment/VideoDetailFragment/VideoDetail.kt
  app/src/main/res/drawable/video_detail_dialog_rounded_image.xml
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/dialog_video_detail_information.xml
Labels: feat

#11 Featuremypage
  app/build.gradle
  app/src/main/java/com/android/youtubeproject/Fragment/MyVideoFragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/Fragment/MyVideoFragment/MyVideoFragmentAdapter.kt
  app/src/main/res/drawable/ic_baseline_content_copy_24.xml
  app/src/main/res/drawable/ic_baseline_more_horiz_24.xml
  app/src/main/res/drawable/ic_baseline_playlist_play_24.xml
  app/src/main/res/drawable/ic_baseline_videocam_24.xml
  app/src/main/res/drawable/logo_appbar.png
  app/src/main/res/drawable/logo_ohjijo.png
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/layout_myvideo_item.xml
Labels: feat

#20 [PACK] : 🎁 [FEAT] : ⚙️[DESIGN] : 🎨 Home: UI,ViewModel,LiveData,패키지이름
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/youtubeproject/API/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/API/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/Constants.kt
  app/src/main/java/com/android/youtubeproject/Fragment/HomeFragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/Fragment/HomeFragment/HomeFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/Fragment/MyVideoFragment/MyVideoFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/Fragment/SearchFragment/SearchFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/Fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/MainActivity.kt
  app/src/main/java/com/android/youtubeproject/ViewModel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/api/CategoryData.kt
  app/src/main/java/com/android/youtubeproject/api/ChannelData.kt
  app/src/main/java/com/android/youtubeproject/api/FavoritesData.kt
  app/src/main/java/com/android/youtubeproject/api/NetWorkClient.kt
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFavoritesAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailFragment.kt
  app/src/main/java/com/android/youtubeproject/interface/ItemClick.kt
  app/src/main/java/com/android/youtubeproject/spf/SPF.kt
  app/src/main/java/com/android/youtubeproject/spf/SearchData.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModelFactory.kt
  app/src/main/java/com/android/youtubeproject/viewpager2adapter/ViewPager2Adapter.kt
  app/src/main/res/layout/activity_video_detail.xml
  app/src/main/res/layout/favoritesitems.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/colors.xml
Labels: bug, documentation, feat, UI, conflict

#23 [PACK] : 🎁 패키지 소문자로 추가 변경
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
Labels: documentation

#25 [FIX] : 🐛[FEAT] : ⚙️ 카테고리(뷰모델,라이브데이터,앱에출력), 패키지명 충돌 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/youtubeproject/api/FavoritesData.kt
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/model/CategoryModel.kt
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/CategoryData.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/FavoritesData.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFavoritesAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailFragment.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/categorymodel/CategoryViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/categorymodel/CategoryViewModelFactory.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModelFactory.kt
  app/src/main/java/com/android/youtubeproject/viewpager2adapter/ViewPager2Adapter.kt
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_video_detail.xml
Labels: bug, feat

#35 [FEAT] : ⚙️ 홈 프래그먼트에서 비디오 상세 액티비티로 데이터 전달
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/res/layout/dialog_video_detail_information.xml
Labels: enhancement

#36 [FIX] : 🐛 함수 인자 위치 변경으로 인해 실행 안되던것 수정.
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
Labels: bug

#37 [FEAT] : 룸 적용 임시 비디오테이블, 유저테이블생성, 유저추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/youtubeproject/api/NetWorkClient.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/CustomDialog.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/DbDao.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyDatabase.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyEntity.kt
  app/src/main/res/drawable/ic_baseline_add_photo_alternate_24.xml
  app/src/main/res/drawable/text_button_bg.xml
  app/src/main/res/layout/dialog_layout.xml
  app/src/main/res/layout/fragment_my_video.xml
Labels: feat

#38 Feature/home
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/model/CategoryModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeNationAdapter.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/categorymodel/CategoryViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModelFactory.kt
Labels: conflict

#39 [CONFLICT] : 💥🚚 conflict해결
  app/src/main/java/com/android/youtubeproject/api/model/NationModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeNationAdapter.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
Labels: conflict

#41 [FEAT] : ⚙️ webview로 영상시청 구현
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/res/drawable/ic_video_detail_more_hori.png
  app/src/main/res/layout/activity_video_detail.xml
Labels: feat

#42 [FEAT] : ⚙️깃허브 풀리퀘 노션의 S.A와 연동(될지 안될지 모름)
  .github/workflows/my_workflow.yml
Labels: enhancement

#44 [FIX] : 🔧 yml파일 삭제, 리드미 추가
  .github/workflows/my_workflow.yml
  README.md
Labels: merge

#45 [FIX] : 🔧 NetWorkInterface : Query -> QueryMap 수정
  app/src/main/java/com/android/youtubeproject/api/HashMapData.kt
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
Labels: feat

#46 [FEAT] : ⚙️ ChannelViewModel 구현중
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/model/NationModel.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/ChannelData.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModelFactory.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
Labels: feat

#52 [DESIGN] : 🎨 Home, [FIX] : 🐛 : 서버데이터가 없을때 "결과가 없습니다" TextView 표시, 예외 처리
  app/src/main/java/com/android/youtubeproject/Constants.kt
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeChannelAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeNationAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
  app/src/main/res/layout/empty_view.xml
  app/src/main/res/layout/favoritesitems.xml
  app/src/main/res/layout/fragment_home.xml
Labels: UI

#54 [FEAT] : ⚙️ 카테고리 클릭 시 라이브데이터를 이용한 로딩프로그레스 구현
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feat, UI

#55 [DESIGN] : 🎨 홈프레그먼트 스크롤뷰 추가, 다이어로그 이미지 수정
  app/src/main/res/layout/dialog_video_detail_information.xml
  app/src/main/res/layout/fragment_home.xml
Labels: UI

#62 [DESIGN] : 🎨(feature/myvideo): 빈화면구현 - Newplaylist 버튼
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/res/drawable/bt_radius10.xml
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/drawable/logoheart.png
  app/src/main/res/layout/fragment_my_video.xml
Labels: UI

#64 ⚙️(feature/myvideo): 뷰페이저 슬라이드 차단
  app/src/main/java/com/android/youtubeproject/MainActivity.kt
Labels: feat
