Repository 5-jojojojojo/5team, pull requests merged in 2023-10, with the labels that each got.

#65 Feature/myvideo 아이콘 추가
  app/src/main/res/drawable/ic_baseline_more_vert_24.xml
  app/src/main/res/drawable/ic_like.png
Labels: UI

#66 마이비디오 저장,삭제,존재여부 추가, 리스트에 데이터바인딩, AAC적용
  app/src/main/java/com/android/youtubeproject/FragmentActionListener.kt
  app/src/main/java/com/android/youtubeproject/MainActivity.kt
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyPageFunc.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/DbDao.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyDatabase.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/db/MyEntity.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/repository/MyVideoRepository.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/viewmodel/MyVideoViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_myvideo_item.xml
Labels: feat

#68 [DESIGN] : 🎨 상세페이지 버튼 아이콘 수정
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/res/drawable/ic_video_detail_dislike_false.png
  app/src/main/res/drawable/ic_video_detail_dislike_true.png
  app/src/main/res/drawable/ic_video_detail_disliked.png
  app/src/main/res/drawable/ic_video_detail_infomation.png
  app/src/main/res/drawable/ic_video_detail_like_false.png
  app/src/main/res/drawable/ic_video_detail_like_true.png
  app/src/main/res/drawable/ic_video_detail_liked.png
  app/src/main/res/drawable/ic_video_detail_more.png
  app/src/main/res/drawable/ic_video_detail_more_hori.png
  app/src/main/res/drawable/ic_video_detail_more_vert.png
  app/src/main/res/drawable/ic_video_detail_share_false.png
  app/src/main/res/drawable/ic_video_detail_share_true.png
  app/src/main/res/drawable/ic_video_detail_shared.png
  app/src/main/res/layout/activity_video_detail.xml
Labels: UI

#69 [FEAT] : ⚙️(feature/myvideo): 비디오 상세에서 좋아요 기능 추가, 마이비디오에서 상세 연결
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/MyVideoFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
Labels: feat

#75 ⚙️🎨 검색페이지: 필수기능 구현&UI
  app/src/main/java/com/android/youtubeproject/Constants.kt
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/ChannelData.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/SearchData.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragmentAdapter.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModelFactory.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/searchitems.xml
Labels: feat, UI

#76 [DESIGN][FIX] : 🎨🔧 앱바 추가&버튼 위치 수정, MVVM패턴 적용중
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModelFactory.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoRepository.kt
  app/src/main/res/layout/activity_video_detail.xml
Labels: UI

#78 [FIX] : 🔧 MVVM패턴 적용중
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoRepository.kt
Labels: feat

#80 [FEAT] : ⚙️ Home : infinity Scroll 구현
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/FavoritesScrollListener.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  build.gradle
Labels: feat

#81 [FEAT] : ⚙️ Home : Detail에서 필요한 데이터 추가
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/FavoritesData.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
Labels: feat

#86 [FEAT] : ⚙️ 스플래쉬 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/youtubeproject/SplashActivity.kt
  app/src/main/res/anim/anim_splash.xml
  app/src/main/res/drawable/logo_ohjijo2.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
Labels: feat

#87 [DOCS] : 📚 Home : 변수명 변경
  app/src/main/java/com/android/youtubeproject/api/model/NationModel.kt
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeNationAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/channelmodel/ChannelViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
Labels: documentation

#89 [FIX] : 🐛 Home : Nation관련 API 중복호출 수정
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
Labels: bug

#91 [FEAT][FIX] : ⚙️🔧 스플래쉬 화면 수정, 홈의 두번째 데이터도 디테일로 넘어가게끔 수정, 데이터 모델 수정
  app/src/main/java/com/android/youtubeproject/SplashActivity.kt
  app/src/main/java/com/android/youtubeproject/api/model/YoutubeModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
  app/src/main/res/anim/anim_splash.xml
  app/src/main/res/anim/anim_splash2.xml
  app/src/main/res/anim/anim_splash3.xml
  app/src/main/res/drawable/ic_logo_removebg.png
  app/src/main/res/drawable/ic_logo_removebg2.png
  app/src/main/res/drawable/ic_logo_removebg3.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_video_detail.xml
Labels: feat

#93 [FEAT] : ⚙️ Search: infinityScroll 기능 구현
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/FavoritesScrollListener.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/SearchScrollListener.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
Labels: feat, UI

#94 [FEAT] : ⚙️ 검색페이지 : 카테고리 선택 추가
  app/src/main/java/com/android/youtubeproject/api/model/CategoryModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/SearchScrollListener.kt
  app/src/main/java/com/android/youtubeproject/method/method.kt
  app/src/main/java/com/android/youtubeproject/spf/SPF.kt
  app/src/main/java/com/android/youtubeproject/spf/SharedPref.kt
  app/src/main/res/drawable/outline.xml
  app/src/main/res/layout/favoritesitems.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feat, UI

#98 Feature/myvide 뷰페이저, 앱 바 부분 수정, 유효성 검사 수정
  app/src/main/java/com/android/youtubeproject/MainActivity.kt
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/myvideofragment/CustomDialog.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/res/drawable/ic_baseline_search_24.xml
  app/src/main/res/layout/dialog_layout.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_video.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feat, UI

#104 [FIX] : 🐛 Home&Search 에러수정
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
  app/src/main/res/layout/favoritesitems.xml
Labels: bug

#106 [FEAT] : ⚙️ 디테일 페이지에서 댓글 볼수있게 수정
  app/src/main/java/com/android/youtubeproject/api/NetWorkInterface.kt
  app/src/main/java/com/android/youtubeproject/api/model/CommentModel.kt
  app/src/main/java/com/android/youtubeproject/api/serverdata/CommentThreadResponse.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailCommentAdapter.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetailViewModel.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoRepository.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/CommentsScrollListener.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/commentitem.xml
  app/src/main/res/layout/dialog_video_detail_information.xml
Labels: feat

#108 [DESIGN] : 🎨 UI변경 : 항목 갯수 표시, UI변경
  app/src/main/java/com/android/youtubeproject/fragment/homefragment/HomeFragment.kt
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragment.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/FavoritesScrollListener.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/NationScrollListener.kt
  app/src/main/java/com/android/youtubeproject/infinityscroll/SearchScrollListener.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/nationviewmodel/NationViewModel.kt
  app/src/main/java/com/android/youtubeproject/viewmodel/searchmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
Labels: feat, UI

#109 [FIX] : 🔧 스플래쉬 화면 조금 수정
  app/src/main/java/com/android/youtubeproject/SplashActivity.kt
  app/src/main/java/com/android/youtubeproject/fragment/videodetailfragment/VideoDetail.kt
  app/src/main/res/layout/activity_splash.xml
Labels: wontfix

#111 [FEAT] : ⚙️ 검색결과예외 처리
  app/src/main/java/com/android/youtubeproject/fragment/searchfragment/SearchFragmentAdapter.kt
Labels: feat

#113 7기_안드로이드_앱개발_심화_팀과제 완료
  README.md
Labels: merge
